### ISSUE TITLE
Plugin Doesn't work in Adobe Illustrator CC 2015.3

### ISSUE THREAD

**Issue by EricKramp** [WestonThayer/Bloks#2]
@WestonThayer, now that I have the plugin compiling I was wondering what the last version number was that the plugin worked. I know you've stated that it's a known issue that it doesn't work in 2015.3.

Do you have a recommended version?

**Comment by WestonThayer** [comment]
It should work fine with one version previous (CC 2015 19.2.1).

**Comment by EricKramp** [comment]
I've got 19.2.1 installed, and the panel loads but it doesn't work. When I uncomment those lines at the very end of the host.jsx file I get this error alert immediately after file load:

`JSX crashed. FileName: 11, Line: 1162, Name: Error, Message: Can only update one BlokContainer at a time!`

**Comment by WestonThayer** [comment]
You mean the `hostscript.jsx` that gets built? Did you uncomment lines that look kinda like this?

``` js
// Append some debugging helpers
contents += "\n\n//loader(7).checkSelectionForRelayout();"
contents += "\n//loader(7).relayoutSelection();"
contents += "\n//loader(7).updateSelectedBlokContainer({ flexDirection: 0, justifyContent: 0, alignItems: 0, flexWrap: 0 });"
contents += "\n//loader(7).createBlokContainerFromSelection({ flexDirection: 0, justifyContent: 0, alignItems: 0, flexWrap: 0 });"
contents += "\n//loader(7).updateSelectedBlok({ flex: undefined, alignSelf: 0 });"
```

Those are only for debugging, you should leave them commented. As long as you have Illustrator pointing to the .aip plugin, you should be good to go now.

**Comment by EricKramp** [comment]
Oh you're right, it was those lines and now it seems to be working. I had uncommented them when trying to determine why I wasn't seeing any changes in the UI after selecting a BlokGroup in your tutorial file.

I see now that I have to hit "Reload" after selecting the BlokGroup, and it seems like uncommenting those lines just was preventing everything else from running.
