### ISSUE TITLE
unable to find com.westonthayer.bloks

### ISSUE THREAD

**Issue by arkany** [WestonThayer/Bloks#3]
Hey Weston, 

I've been showing off the plugin to everyone in the office. We're crazy excited. However, I'm not sure where to find the com.westonthayer.bloks - do I need to download XCode and get it spun up in there?

**Comment by WestonThayer** [comment]
Sweet! Keep me posted :)

Did you download [this zip](https://github.com/WestonThayer/Bloks/releases/download/v0.1.1/bloks.zip)? `com.westonthayer.bloks` should be the name of a folder in there. If it isn't, can you send me a screenshot of what Finder shows after you unzip?

**Comment by arkany** [comment]
Thx for the help! 

Here's what I'm seeing:
![screen shot 2016-08-05 at 10 44 01 am](https://cloud.githubusercontent.com/assets/192032/17445391/a173fdd8-5af9-11e6-8700-7a8864eb36b0.png)

**Comment by WestonThayer** [comment]
Resolved offline. For others, this is the source, not the binary installer. Make sure you follow [steps 1-4](https://github.com/WestonThayer/Bloks#installation).
